# Introduction

In recent years, there has been a growing interest in the use of “big data” sources in official statistics (Daas et al., 2015). The ever-growing number of sensors in electronic devices generate large amounts of individual digital tracks, both with a high frequency and at a fine spatial resolution. As a result, there is a high potential in combining these data with traditional official statistics sources, like surveys or administrative data (Cheung, 2012). Such combination could reduce delays in access to relevant information (e.g. short-term economic circumstances), enable the production of information at a more disaggregated level, and reduce data collection costs.

Due to their ubiquitous use in general population, data generated by mobile communication technologies appear as a high potential source for official statistics. For each mobile event, a timestamp and a location are collected. The aggregation of all these events provides information on population distribution, with fine-level spatial and temporal resolution. Consequently, mobile phone data have been used with success in various applications. In particular, they appear as a major new data source for traditional fields of study of human and social behavior, such as mobility patterns (Calabrese et al., 2013), modes of transport (Demissie et al., 2016), and the analysis of social and spatial segregation (Galiana et al., 2018). 

Due to their dynamic nature, these data provide the opportunity to proceed to present population counts (in a given venue, city, region...) whereas official statistics sources, notably census data, mostly produce information on resident population (Terrier, 2009). Yet, information on the evolution of present population evolution over time has potential use for a wide variety of actors. It provides knowledge on changes in population densities which are due to tourism (Vanhoof et al., 2017) and national or international migration flows (Hugues et al., 2016). It it used to study attendance patterns of particular areas, which are useful to analyze territorial dynamics (Toole et al., 2012). Such temporal variations also appear very important for local and regional actors, who seek to adapt supply of local services (transport, emergency, etc.) to demand.

Multiple challenges arise with the use of mobile phone data for official statistics. The most obvious one is the necessity to ensure confidentiality of collected data by avoiding possibility to identify individuals. Another difficulty is to proceed the huge amounts of data collected by mobile phone, which requires specific and robust IT infrastructures. In this study, we are tackling another important challenge : the geographical location of events. In most applications involving mobile phone data, only the location of the antenna to which a device has connected to is available, leaving the exact geographical location of mobile devices unknown (Ricciato et al., 2015). As a result, researchers working on population estimation using mobile phone data often rely on the Voronoi tessellation approximation (Okabe et al., 2009) : when a phone event is observed, it is assumed that the device connects to the nearest antenna (see for instance Deville et al., 2014 ; Vanhoof et al., 2018). However, there are many downsides to using this hypothesis to estimate the geographical location of events (Ricciato et al., 2017 ; Sakarovitch et al., 2019). These shortcomings have the potential to cause important bias in studies relying on this hypothesis. 

In this paper, we implement a probabilistic method for the detection of devices location, based on a bayesian model developed by Tennekes (2018). The main advantage of this method is that it is highly flexible, in the sense that it can accomodate a wide range of situations as regards availability of technical information on antennae. In this study, we focus on the case mostly found in the literature in which no technical information on antennae are available. The bayesian framework makes it possible to map events observed at Voronoi level on a regular grid in a probabilized way. This transition enables us to make use of available prior information on the grid, which allows localization of phone users to depart from a purely Voronoi based one. We implement this model on an extensively studied data set consisting in call detail records (CDR) of French MNO Orange customers in 2007. Land use data is mobilized as prior information. Validation is performed by comparing population estimates to French localized tax data, from which we get the number of people legally residing in each tile of the grid. Using multiple metrics, we provide evidence that the bayesian model substantially improves population estimates as compared to baseline. Besides, we use spatial analysis tools to demonstrate that the spatial structure of residential population is better replicated. Yet, we show that the gain in quality mainly occurs in rural and peri-urban areas, whereas densely populated areas remain poorly estimated. We discuss these limitations and explain how technical information on antennae as well was signalling data could be included in the bayesian model to further improve population counts.


