# Conclusion

Mobile phone data appear as a high potential source to complement traditional ways of counting population. However, the lack of technical information on antennae has led researchers to rely on Voronoi approximation in most applications, which can introduce major bias. Our main contribution is to show that a simple bayesian model of localization can substantially improve population estimation by enabling the combination of mobile phone data and other statistical sources. We also point out that the indicators of estimation quality which have been used in previous studies — mainly Pearson's r correlation coefficient — can be misleading due to the pecularities of population distributions. Finally, we show that tools from spatial analysis and fractal geometry theory can be used to evaluate the quality gain of new estimates as regards replication of the spatial structure of validation data. 

In this paper, we focused on *resident* population estimation in order to validate new estimates against localized tax data. But it is our opinion that the main potential of mobile phone data is to enable the estimation of *present* population, which sources from official statistics fail to measure satisfactorily. A main advantage of the bayesian framework is that it can accomodate a wide range of situations as regards information availability. As such, we would suggest future research to take advantage of this flexibility by estimating new configurations of the model, for instance with additional technical information on antennae (best service areas, radio propagation models) or different prior information sources (transport infrastructure, points of interest, etc.). Further investigation is also needed to determine how to validate present population estimates as sources based on census are not sufficient anymore for this purpose.